# Generated by Django 4.2.5 on 2023-09-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pc', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
                ('processor_work', models.CharField(max_length=200)),
                ('cores', models.CharField(max_length=20)),
                ('name_videocard', models.CharField(max_length=200)),
                ('memory_videocard', models.CharField(max_length=200)),
                ('temperature_videocard', models.CharField(max_length=20)),
                ('work_videocard', models.CharField(max_length=20)),
                ('Mb_name', models.CharField(max_length=200)),
                ('Mb_socket', models.CharField(max_length=200)),
                ('Mb_Ram_memory', models.CharField(max_length=200)),
                ('Mb_Ram_mhz', models.CharField(max_length=200)),
                ('Hdd', models.TextField()),
            ],
        ),
    ]
