# Generated by Django 4.2.5 on 2023-09-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_user',
            name='Mb_Ram_memory',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info_user',
            name='Mb_Ram_mhz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info_user',
            name='Mb_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info_user',
            name='Mb_socket',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info_user',
            name='cores',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='info_user',
            name='memory_videocard',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info_user',
            name='name_pc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info_user',
            name='name_videocard',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info_user',
            name='processor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info_user',
            name='processor_work',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='info_user',
            name='temperature_videocard',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='info_user',
            name='work_videocard',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
