# Generated by Django 4.2.5 on 2023-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_info_user_work_videocard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_user',
            name='work_videocard',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
