# Generated by Django 4.2.5 on 2023-09-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_info_user_work_videocard'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_user',
            name='build_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='info_user',
            name='version_windows',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
