# Generated by Django 4.2.5 on 2023-09-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_info_user_build_number_info_user_version_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_user',
            name='ip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='info_user',
            name='mac',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='info_user',
            name='work_system_non_stop',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
